xi <- (0:360)*pi/180
Ec <- data.frame ("xi"=xi)
EL <- data.frame ("xi"=xi)
ER <- data.frame ("xi"=xi)
Ec$WSfit <- cfcircleC[1] + cfcircleC[2] * cos(xi)+cfcircleC[3]*mean(Dc$TASX, na.rm=TRUE)*sin(xi)
EL$WSfit <- cfcircleL[1] + cfcircleL[2] * cos(xi)+cfcircleL[3]*mean(DL$TASX, na.rm=TRUE)*sin(xi)
ER$WSfit <- cfcircleR[1] + cfcircleR[2] * cos(xi)+cfcircleR[3]*mean(DR$TASX, na.rm=TRUE)*sin(xi)
clr <- c("left", "right", "std")
col <- c ('blue', 'darkgreen')
EBL <- binStats (DL[, c("WSC", "xi")], bins=30)
EBL$xc <- EBL$xc / Cradeg
EBR <- binStats (DR[, c("WSC", "xi")], bins=30)
EBR$xc <- EBR$xc / Cradeg
EBc <- binStats (Dc[, c("WSC", "xi")], bins=30)
EBc$xc <- EBc$xc / Cradeg
p <- ggplot(EBL, aes(x=xc))
p <- p + geom_errorbar(aes(ymin=ybar-sigma, ymax=ybar+sigma, colour=clr[1]))+ylim(ymin, ymax)
p <- p + scale_x_continuous (breaks=c(0,90,180,270,360))
p <- p + geom_point (aes(y = ybar, colour=clr[1], shape=clr[1]), size=2.5)
p <- p + geom_line  (data=EL, aes(x=xi/Cradeg, y=WSfit), colour='darkorange', lty=1, lwd=1.5)
p <- p + geom_errorbar(data=EBR, aes(ymin=ybar-sigma, ymax=ybar+sigma, colour=clr[2]))
p <- p + geom_point (data=EBR, aes(y = ybar, colour=clr[2], shape=clr[2]), size=2.5)
p <- p + geom_line  (data=ER, aes(x=xi/Cradeg, y=WSfit), colour='darkorange', lty=1, lwd=1.5)
# p <- p + geom_errorbar(data=EBc, aes(ymin=ybar-sigma, ymax=ybar+sigma), col='red')
# p <- p + geom_point (aes(y = ybar), pch=19, col='red', size=2.5)
# p <- p + geom_line  (data=Ec, aes(x=xi/Cradeg, y=WSfit), colour='darkorange', lty=2, lwd=2)
p <- p + xlab(expression(paste(xi," [", degree, "]"))) + ylab ("wind speed [m/s]")
p <- p + scale_colour_manual("turn direction:", labels = clr, values = col)
p <- p + scale_shape_manual ("turn direction:", labels = clr, values = c(19,19))
p <- p + theme_WAC() + theme (legend.background=element_rect(colour='black', size=0.3, fill="ivory")) 
print (p)
# left turns:
DL$SA <- sin(DL$Ang*pi/180.)
DL$CA <- cos(DL$Ang*pi/180.)
fm1 <- lm (WS~SA+CA, data=DL)
cf1 <- coefficients(fm1)
clr = c("fit", "measurements", "fit")
col = c("darkorange", "blue", "darkorange")
g <- ggplot(data=DL, aes(x=Ang, y=WS))
g <- g + geom_point(colour=col[2], size=2, aes(shape="measurements")) 
g <- g + geom_line(aes(y=cf1[1]+cf1[2]*sin(DL$Ang*pi/180.)+cf1[3]*cos(DL$Ang*pi/180.),  colour=clr[1]), lwd=3)
g <- g + scale_colour_manual("", labels = clr, values = col)
g <- g + scale_shape_manual ("", labels="measurements", values=19)
g <- g + xlab("Heading - Wind Dir.") + ylab("Wind Speed [m/s]")+theme_WAC()     
g <- g + theme(legend.position=c(0.7,0.94))
## g
#plot (Ang[rs], WS[rs], pch=19, col='blue')
#lines(c(180,180), c(0.,50.), col='red', lwd=2)
#lines(c(0,0), c(0.,50.), col='red', lwd=2)
#lines(c(90,90), c(0.,50.), col='red', lwd=2)
#lines(c(270,270), c(0.,50.), col='red', lwd=2)
#lines(c(360,360), c(0.,50.), col='red', lwd=2)
#lines(Ang[rs], cf1[1]+cf1[2]*sin(Ang[rs]*pi/180.)+cf1[3]*cos(Ang[rs]*pi/180.), col='darkorange', lwd=4)
